tap "heroku/brew"
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/services"
brew "autojump"
brew "git"
brew "node"
brew "nvm"
brew "python@2"
brew "rbenv"
brew "redis", restart_service: true
brew "yarn"
brew "zsh"
brew "heroku/brew/heroku"
cask "dropbox"
cask "firefox"
